Addressed PR #1551 comments
* Added NODE_VERSION and NEWMAN_VERSION (formerly newman_version) as build args
* Used a default NODE_VERSION value of 8

diff --git a/docker/images/alpine33/Dockerfile b/docker/images/alpine33/Dockerfile
--- a/docker/images/alpine33/Dockerfile
+++ b/docker/images/alpine33/Dockerfile
@@ -1,29 +1,33 @@
 FROM alpine:3.3
 MAINTAINER Postman Labs <help@getpostman.com>
 
-ARG newman_version
-# Bail out early if NODE_VERSION is not provided
-RUN if [ ! $(echo $newman_version | grep -oE "^[0-9]+\.[0-9]+\.[0-9]+$") ]; then \
-        echo "\033[0;31mA valid semver Newman version is required in the newman_version build-arg\033[0m"; \
-        exit 1; \
-    fi
-
-ENV NODE_VERSION 8.11.2
-
-# Install node
-RUN echo -e "http://nl.alpinelinux.org/alpine/v3.3/main\nhttp://nl.alpinelinux.org/alpine/v3.3/community" > /etc/apk/repositories && \
-    apk add --update --no-cache libgcc libstdc++;
-
-ADD https://github.com/oznu/alpine-node/releases/download/${NODE_VERSION}/node-v${NODE_VERSION}-linux-x86_64-alpine.tar.gz /opt/node-${NODE_VERSION}.tar.gz
-
-RUN tar -xzf /opt/node-${NODE_VERSION}.tar.gz -C /usr --no-same-owner && \
-    rm /opt/node-${NODE_VERSION}.tar.gz;
+ARG NODE_VERSION=8
+ARG NEWMAN_VERSION
 
 # Set environment variables
-ENV LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8" NEWMAN_VERSION=$newman_version
+ENV LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8" ALPINE_NODE_REPO="oznu/alpine-node"
 
-# Install newman
-RUN npm install -g newman@${NEWMAN_VERSION};
+# Bail out early if NODE_VERSION is not provided
+RUN if [ ! $(echo $NEWMAN_VERSION | grep -oE "^[0-9]+\.[0-9]+\.[0-9]+$") ]; then \
+        echo "\033[0;31mA valid semver Newman version is required in the NEWMAN_VERSION build-arg\033[0m"; \
+        exit 1; \
+    fi && \
+    # Add the latest Alpine Linux package to the repositories list
+    echo -e "http://nl.alpinelinux.org/alpine/v3.3/main\nhttp://nl.alpinelinux.org/alpine/v3.3/community" > /etc/apk/repositories && \
+    # Update existing packages and install Node dependencies
+    apk add --update --no-cache libgcc libstdc++ jq curl && \
+    # Determine the complete Semver Node version for the provided Node major version in $NODE_VERSION
+    FULL_NODE_VERSION=$(curl --silent "https://api.github.com/repos/${ALPINE_NODE_REPO}/releases" | jq -r '.[].tag_name' | grep -oE "^${NODE_VERSION}\.\d+\.\d+$" | sort -r -t. -k 1,1nr -k 2,2nr -k 3,3nr | head -n1) && \
+    # Download the appropriate Node binary for Alpine Linux
+    curl --silent -L "https://github.com/${ALPINE_NODE_REPO}/releases/download/${FULL_NODE_VERSION}/node-v${FULL_NODE_VERSION}-linux-x86_64-alpine.tar.gz" > /etc/alpine-node-${NODE_VERSION}.tar.gz && \
+    # Extract and install Node from the binary downloaded in the previous step
+    tar -xzf /etc/alpine-node-${NODE_VERSION}.tar.gz -C /usr --no-same-owner && \
+    # Install Newman globally
+    npm install --global newman@${NEWMAN_VERSION} && \
+    # Prune redundant packages
+    apk del jq curl && \
+    # Clear Alpine Node binary
+    rm /etc/alpine-node-${NODE_VERSION}.tar.gz;
 
 # Set workdir to /etc/newman
 # When running the image, mount the directory containing your collection to this location
