Updated Newman alpine 3.3 Dockerfile for automated postpublish
* Switched to installing Node from the debian nodesource repository
* Compacted multiple ENV statements
* Added validation for build-args

diff --git a/docker/images/ubuntu1404/Dockerfile b/docker/images/ubuntu1404/Dockerfile
--- a/docker/images/ubuntu1404/Dockerfile
+++ b/docker/images/ubuntu1404/Dockerfile
@@ -1,32 +1,25 @@
 FROM ubuntu:14.04.2
 MAINTAINER Postman Labs <help@getpostman.com>
 
-# Install curl and npm
-
-RUN apt-get install -y curl;
-
-RUN curl -sS https://deb.nodesource.com/setup_8.x | sudo -E bash -
-
-RUN apt-get clean && apt-get upgrade -y && apt-get update -y --fix-missing && apt-get install -y nodejs
+ARG newman_version
+# Bail out early if NODE_VERSION is not provided
+RUN if [ ! $(echo $newman_version | grep -oE "^[0-9]+\.[0-9]+\.[0-9]+$") ]; then \
+        echo "\033[0;31mA valid semver Newman version is required in the newman_version build-arg\033[0m"; \
+        exit 1; \
+    fi
 
 # Set node version
 ENV NODE_VERSION 8
 
-# Set locale
-ENV LC_ALL en_US.UTF-8
-ENV LANG en_US.UTF-8
-ENV LANGUAGE en_US.UTF-8
-
 # Install node
-RUN npm install -g n;
-RUN n ${NODE_VERSION};
+ADD https://deb.nodesource.com/setup_$NODE_VERSION.x /opt/install_node.sh
+RUN bash /opt/install_node.sh && apt-get install -y nodejs
 
-ARG newman_version
-ENV NEWMAN_VERSION=$newman_version
+# Set environment variables
+ENV LC_ALL="en_US.UTF-8" LANG="en_US.UTF-8" LANGUAGE="en_US.UTF-8" NEWMAN_VERSION=$newman_version
 
 # Install newman
 RUN npm install -g newman@${NEWMAN_VERSION};
-
 
 # Set workdir to /etc/newman
 # When running the image, mount the directory containing your collection to this location
@@ -36,7 +29,6 @@ RUN npm install -g newman@${NEWMAN_VERSION};
 # In case you mount your collections directory to a different location, you will need to give absolute paths to any
 # collection, environment files you want to pass to newman, and if you want newman reports to be saved to your disk.
 # Or you can change the workdir by using the -w or --workdir flag
-
 WORKDIR /etc/newman
 
 # Set newman as the default container command
@@ -45,5 +37,4 @@ WORKDIR /etc/newman
 # docker run -v /home/collections:/etc/newman -t postman/newman_ubuntu1404 -c YourCollection.json.postman_collection \
 #                                                                          -e YourEnvironment.postman_environment \
 #                                                                          -H newman_report.html
-
 ENTRYPOINT ["newman"]
